export interface ThemeColors {
  primary: string;
  primaryLight: string;
  primaryDark: string;
  secondary: string;
  secondaryLight: string;
  accent: string;
  accentLight: string;
  background: string;
  surface: string;
  surfaceAlt: string;
  text: string;
  textSecondary: string;
  textLight: string;
  border: string;
  borderLight: string;
  success: string;
  warning: string;
  error: string;
  white: string;
  shadow: string;
  cardGradientStart: string;
  cardGradientEnd: string;
  chatBubbleUser: string;
  chatBubbleAI: string;
  tabBar: string;
  tabBarBorder: string;
  tabActive: string;
  tabInactive: string;
  inputBackground: string;
  modalBackground: string;
  overlayBackground: string;
  scheduleDayBg: string;
  scheduleDayTodayBg: string;
  undoBg: string;
  medCardTakenBg: string;
  completedBadgeBg: string;
}

export const lightColors: ThemeColors = {
  primary: '#0D9488',
  primaryLight: '#CCFBF1',
  primaryDark: '#0F766E',
  secondary: '#F97066',
  secondaryLight: '#FEE2E2',
  accent: '#F59E0B',
  accentLight: '#FEF3C7',
  background: '#F8FAF9',
  surface: '#FFFFFF',
  surfaceAlt: '#F0FDF4',
  text: '#1A1A2E',
  textSecondary: '#64748B',
  textLight: '#94A3B8',
  border: '#E2E8F0',
  borderLight: '#F1F5F9',
  success: '#10B981',
  warning: '#F59E0B',
  error: '#EF4444',
  white: '#FFFFFF',
  shadow: '#0D9488',
  cardGradientStart: '#F0FDFA',
  cardGradientEnd: '#FFFFFF',
  chatBubbleUser: '#0D9488',
  chatBubbleAI: '#F1F5F9',
  tabBar: '#FFFFFF',
  tabBarBorder: '#E2E8F0',
  tabActive: '#0D9488',
  tabInactive: '#94A3B8',
  inputBackground: '#F8FAF9',
  modalBackground: '#FFFFFF',
  overlayBackground: 'rgba(0,0,0,0.5)',
  scheduleDayBg: '#F8FAFC',
  scheduleDayTodayBg: '#F0FDF4',
  undoBg: '#F1F5F9',
  medCardTakenBg: '#F0FDF4',
  completedBadgeBg: '#DCFCE7',
};

export const darkColors: ThemeColors = {
  primary: '#14B8A6',
  primaryLight: '#134E4A',
  primaryDark: '#5EEAD4',
  secondary: '#F97066',
  secondaryLight: '#4C1D1D',
  accent: '#F59E0B',
  accentLight: '#3D2E06',
  background: '#0F1419',
  surface: '#1A2332',
  surfaceAlt: '#1C2D2A',
  text: '#E8ECF0',
  textSecondary: '#8899AA',
  textLight: '#5C6E7F',
  border: '#2A3A4A',
  borderLight: '#1E2D3D',
  success: '#10B981',
  warning: '#F59E0B',
  error: '#EF4444',
  white: '#FFFFFF',
  shadow: '#000000',
  cardGradientStart: '#1A2332',
  cardGradientEnd: '#0F1419',
  chatBubbleUser: '#0D9488',
  chatBubbleAI: '#1E2D3D',
  tabBar: '#141D26',
  tabBarBorder: '#1E2D3D',
  tabActive: '#14B8A6',
  tabInactive: '#5C6E7F',
  inputBackground: '#1E2D3D',
  modalBackground: '#1A2332',
  overlayBackground: 'rgba(0,0,0,0.7)',
  scheduleDayBg: '#1E2D3D',
  scheduleDayTodayBg: '#1C2D2A',
  undoBg: '#1E2D3D',
  medCardTakenBg: '#1C2D2A',
  completedBadgeBg: '#1C2D2A',
};

const Colors = lightColors;
export default Colors;
